### ISSUE TITLE
[feat]: Dijkstra's algorithm

### ISSUE THREAD

**Issue by Parvezkhan0** [puruagarwal1/python_dir#24]
You are given a weighted directed graph represented as an adjacency list. Each node in the graph is labeled with a unique integer. Write a Python function shortest_path that finds the shortest path from a given source node to a destination node using Dijkstra's algorithm.

**Comment by Parvezkhan0** [comment]
Assign me this issue as a part of me hacktoberefest contribution

**Comment by puruagarwal1** [comment]
plz star this repo

**Comment by Parvezkhan0** [comment]
sure, I will give a star to your repo just help me to win this hacktoberfest 
I am making some issue assign those issue to me and label it hacktoberfest
