### ISSUE TITLE
I would like to add BFS and DFS implementation in python

### ISSUE THREAD

**Issue by Niyati3031** [puruagarwal1/python_dir#3]
Can you assign this to me for Hacktoberfest 2023

**Comment by harshmishra19** [comment]
@puruagarwal1 Please assign me to this issue; I would like to work on it

**Comment by puruagarwal1** [comment]
@harshmishra19 the issue assign is on first come first bases if @Niyati3031 didn't upgrade the open source this issue will automatically assign to u in 7 days.

**Comment by harshmishra19** [comment]
@puruagarwal1 okay
